module.exports = {
  USER_DIRECTIVE_MODULE: 'wfm.user.directives',
  USER_MODULE_ID: "wfm.user",
  USER_SERViCE: 'wfm.user.services',
  WORKORDER_ENTITY_NAME: "workorders",
  RESULTS_ENTITY_NAME: "results",
  WORKFLOWS_ENTITY_NAME: "workflows",
  USERS_ENTITY_NAME: "users",
  MEMBERSHIP_ENTITY_NAME: "membership",
  GROUP_ENTITY_NAME: "group",
  TOPIC_PREFIX: "wfm",
  ERROR_PREFIX: "error",
  DONE_PREFIX: "done",
  TOPIC_TIMEOUT: 2000,
  TOPICS: {
    CREATE: "create",
    UPDATE: "update",
    LIST: "list",
    REMOVE: "remove",
    READ: "read",
    START: "start",
    STOP: "stop",
    FORCE_SYNC: "force_sync",
    SYNC_COMPLETE: "sync_complete",
    HAS_SESSION: "has_session",
    AUTHENTICATE: "authenticate",
    CLEAR_SESSION: "clear_session",
    READ_PROFILE: "read_profile"
  }
};